import React, { Component } from 'react';

class SeachBar extends Component {
  // this part generated by JSX in sublime
  // constructor(props) {
  //   super(props);
  //   this.displayName = 'SeachBar';
  // }
  // refactoring this
  // render() {
  //   return <div><input onChange = {this.onInputChange} /></div>;
  // }

  // onInputChange(event) {
  //   console.log(event.target.value);
  // }
  render() {
    return (
      <div>
        <input onChange = {event => console.log(event.target.value)} />
      </div>
      );
  }
}

export default SeachBar;

